const lessonTitle = "两张纸条";

const lessonData = [
    // ===== 第 1 段 =====
    ["那天", "nà tiān", "That day", "Pada hari itu"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["骑着", "qí zhe", "riding", "menunggang"],
    ["自行车", "zì xíng chē", "bicycle", "basikal"],
    ["从外面", "cóng wài miàn", "from outside", "dari luar"],
    ["回来", "huí lái", "came back", "pulang"],
    ["，", "", "", ""],
    ["一进门", "yí jìn mén", "as soon as entering", "sebaik sahaja masuk"],
    ["就", "jiù", "then", "lalu"],
    ["大呼小叫", "dà hū xiǎo jiào", "shout excitedly", "berseru-seru"],
    ["地说", "de shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["遇到了", "yù dào le", "met", "bertemu"],
    ["好人", "hǎo rén", "good person", "orang baik"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["见我", "jiàn wǒ", "seeing me", "melihat saya"],
    ["没反应", "méi fǎn yìng", "no response", "tiada reaksi"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["坐在", "zuò zài", "sat on", "duduk di"],
    ["沙发上", "shā fā shàng", "on the sofa", "atas sofa"],
    ["，", "", "", ""],
    ["自顾自地", "zì gù zì de", "to oneself", "bersendirian"],
    ["絮叨", "xù dāo", "chatter / ramble", "berceloteh"],
    ["起来", "qǐ lái", "started to", "mula"],
    ["。", "", "", ""],
    ["原本", "yuán běn", "originally", "pada asalnya"],
    ["不当一回事", "bú dàng yí huí shì", "didn't take it seriously", "tidak mengambil berat"],
    ["的我", "de wǒ", "I", "saya"],
    ["，", "", "", ""],
    ["听见", "tīng jiàn", "heard", "terdengar"],
    ["“", "", "", ""],
    ["那人", "nà rén", "that person", "orang itu"],
    ["把我的", "bǎ wǒ de", "my", "saya punya"],
    ["自行车", "zì xíng chē", "bicycle", "basikal"],
    ["撞歪了", "zhuàng wāi le", "knocked crooked", "melanggar hingga senget"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["这才", "zhè cái", "only then", "baru"],
    ["把头", "bǎ tóu", "head", "kepala"],
    ["转向", "zhuǎn xiàng", "turned towards", "memusingkan ke arah"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["，", "", "", ""],
    ["发现", "fā xiàn", "discovered", "mendapati"],
    ["她", "tā", "she", "dia"],
    ["衣服上", "yī fu shàng", "on her clothes", "pada pakaiannya"],
    ["满是", "mǎn shì", "full of", "penuh dengan"],
    ["尘土", "chén tǔ", "dust", "habuk"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["却", "què", "however", "namun"],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["捡了便宜", "jiǎn le pián yi", "got a bargain", "berasa bernasib baik"],
    ["似的", "shì de", "as if", "seakan-akan"],
    ["，", "", "", ""],
    ["仍", "réng", "still", "masih"],
    ["滔滔不绝", "tāo tāo bù jué", "talk endlessly", "bercakap tanpa henti"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["“", "", "", ""],
    ["马路上", "mǎ lù shàng", "On the road", "Di jalan raya"],
    ["一个人", "yí gè rén", "not a single person", "seorang pun"],
    ["也没有", "yě méi yǒu", "also no", "tiada"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["原本", "yuán běn", "originally", "sepatutnya"],
    ["可以", "kě yǐ", "could", "boleh"],
    ["一走了之", "yì zǒu liǎo zhī", "walk away", "pergi begitu sahaja"],
    ["，", "", "", ""],
    ["却", "què", "yet", "tetapi"],
    ["停下", "tíng xià", "stopped", "berhenti"],
    ["车子", "chē zi", "vehicle", "kenderaan"],
    ["，", "", "", ""],
    ["跑过来", "pǎo guò lái", "ran over", "berlari ke mari"],
    ["扶我", "fú wǒ", "helped me", "menolong saya"],
    ["，", "", "", ""],
    ["问我", "wèn wǒ", "asked me", "bertanya saya"],
    ["摔伤了没有", "shuāi shāng le méi yǒu", "if I was injured", "adakah cedera"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["踢踢腿", "tī tī tuǐ", "kicked my legs", "menendang-nendang kaki"],
    ["，", "", "", ""],
    ["甩甩手", "shuǎi shuǎi shǒu", "swung my arms", "mengibas-ngibas tangan"],
    ["，", "", "", ""],
    ["告诉", "gào su", "told", "memberitahu"],
    ["他", "tā", "him", "dia"],
    ["没事", "méi shì", "it's nothing", "tiada apa"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["仍然", "réng rán", "still", "masih"],
    ["不走", "bù zǒu", "did not leave", "tidak pergi"],
    ["，", "", "", ""],
    ["非让", "fēi ràng", "insisted on", "mesti menyuruh"],
    ["我", "wǒ", "me", "saya"],
    ["走几步", "zǒu jǐ bù", "walk a few steps", "berjalan beberapa langkah"],
    ["给他", "gěi tā", "for him", "untuk dia"],
    ["看看", "kàn kan", "see", "lihat"],
    ["。", "", "", ""],
    ["确定", "què dìng", "confirmed", "memastikan"],
    ["我真的", "wǒ zhēn de", "I really", "saya benar-benar"],
    ["没事后", "méi shì hòu", "after okay", "selepas tiada apa-apa"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["把我", "bǎ wǒ", "me", "saya"],
    ["扶上", "fú shàng", "helped onto", "membantu naik"],
    ["自行车", "zì xíng chē", "bicycle", "basikal"],
    ["，", "", "", ""],
    ["要我", "yào wǒ", "asked me", "minta saya"],
    ["试试看", "shì shi kàn", "try and see", "cubalah"],
    ["车", "chē", "bike", "basikal"],
    ["摔坏了没有", "shuāi huài le méi yǒu", "if damaged", "adakah rosak"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["我以为", "wǒ yǐ wéi", "I thought", "Saya menyangka"],
    ["妈", "mā", "mom", "ibu"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["说完了", "shuō wán le", "finished talking", "habis bercerita"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["喝了", "hē le", "drank", "minum"],
    ["一口水", "yì kǒu shuǐ", "a sip of water", "seteguk air"],
    ["又", "yòu", "again", "lagi"],
    ["继续说", "jì xù shuō", "continued", "menyambung cerita"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你说", "nǐ shuō", "you tell me", "cakaplah"],
    ["一个大男人", "yí gè dà nán rén", "a grown man", "seorang lelaki dewasa"],
    ["怎么", "zěn me", "how", "macam mana"],
    ["婆婆妈妈", "pó po mā mā", "so fussy", "begitu cerewet"],
    ["的", "de", "", ""],
    ["？", "", "", ""],
    ["于是", "yú shì", "so", "Maka"],
    ["我", "wǒ", "I", "saya"],
    ["让他", "ràng tā", "let him", "menyuruh dia"],
    ["回去", "huí qù", "go back", "balik"],
    ["，", "", "", ""],
    ["我也", "wǒ yě", "I also", "saya pun"],
    ["骑上", "qí shàng", "mounted", "menaiki"],
    ["自行车", "zì xíng chē", "bicycle", "basikal"],
    ["要", "yào", "was about to", "hendak"],
    ["回家", "huí jiā", "go home", "pulang rumah"],
    ["准备", "zhǔn bèi", "prepare", "menyediakan"],
    ["晚饭", "wǎn fàn", "dinner", "makan malam"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["谁知道", "shuí zhī dào", "who knew", "siapa sangka"],
    ["他", "tā", "he", "dia"],
    ["又", "yòu", "again", "lagi"],
    ["追了上来", "zhuī le shàng lái", "chased after me", "mengejar ke mari"],
    ["，", "", "", ""],
    ["塞给我", "sāi gěi wǒ", "shoved to me", "menyodok kepada saya"],
    ["一张", "yì zhāng", "a", "sehelai"],
    ["纸条", "zhǐ tiáo", "note", "nota"],
    ["，", "", "", ""],
    ["说是", "shuō shì", "said it was", "katanya itu"],
    ["他的", "tā de", "his", "dia punya"],
    ["联络号码", "lián luò hào mǎ", "contact number", "nombor hubungan"],
    ["………", "", "", ""],
    ["”", "", "", ""],
    ["这时", "zhè shí", "At this moment", "Pada masa ini"],
    ["我", "wǒ", "I", "saya"],
    ["赶忙", "gǎn máng", "hurriedly", "cepat-cepat"],
    ["问", "wèn", "asked", "bertanya"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["纸条", "zhǐ tiáo", "the note", "nota itu"],
    ["呢", "ne", "particle", "?"],
    ["？”", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["却", "què", "however", "namun"],
    ["说", "shuō", "said", "berkata"],
    ["弄丢了", "nòng diū le", "lost it", "hilang"],
    ["。", "", "", ""],
    ["说完", "shuō wán", "after saying", "selepas berkata"],
    ["站起身来", "zhàn qǐ shēn lái", "stood up", "berdiri"],
    ["就往", "jiù wǎng", "and went towards", "terus ke arah"],
    ["厨房", "chú fáng", "kitchen", "dapur"],
    ["走", "zǒu", "walked", "berjalan"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["发出", "fā chū", "let out", "mengeluarkan"],
    ["一声", "yì shēng", "a sound", "satu bunyi"],
    ["“", "", "", ""],
    ["叮咚", "dīng dōng", "ding dong", "ding dong"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["吓了我一跳", "xià le wǒ yí tiào", "startled me", "mengejutkan saya"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["流露出", "liú lù chū", "showed", "menzahirkan"],
    ["痛苦的", "tòng kǔ de", "painful", "kesakitan"],
    ["神情", "shén qíng", "expression", "raut wajah"],
    ["，", "", "", ""],
    ["朝我", "cháo wǒ", "towards me", "ke arah saya"],
    ["摆摆手", "bǎi bǎi shǒu", "waved her hand", "melambai-lambai tangan"],
    ["。", "", "", ""],
    ["第二天", "dì èr tiān", "The next day", "Keesokan harinya"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["就", "jiù", "then", "pun"],
    ["起不了床了", "qǐ bù liǎo chuáng le", "could not get out of bed", "tidak dapat bangun dari katil"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["我立即", "wǒ lì jí", "I immediately", "Saya segera"],
    ["把母亲", "bǎ mǔ qīn", "mother", "ibu"],
    ["送进", "sòng jìn", "sent to", "menghantar ke"],
    ["医院", "yī yuàn", "hospital", "hospital"],
    ["。", "", "", ""],
    ["检查", "jiǎn chá", "examination", "pemeriksaan"],
    ["完毕后", "wán bì hòu", "after completion", "selepas selesai"],
    ["，", "", "", ""],
    ["医生", "yī shēng", "doctor", "doktor"],
    ["说得", "shuō de", "said that", "berkata bahawa"],
    ["马上", "mǎ shàng", "immediately", "segera"],
    ["做", "zuò", "do", "menjalankan"],
    ["紧急", "jǐn jí", "emergency", "kecemasan"],
    ["手术", "shǒu shù", "surgery", "pembedahan"],
    ["。", "", "", ""],
    ["我在", "wǒ zài", "I while", "Saya semasa"],
    ["办理", "bàn lǐ", "handling", "mengurus"],
    ["住院", "zhù yuàn", "hospital admission", "kemasukan hospital"],
    ["手续时", "shǒu xù shí", "procedures when", "prosedur ketika"],
    ["，", "", "", ""],
    ["不停地", "bù tíng de", "continuously", "tanpa henti"],
    ["抱怨", "bào yuàn", "complain", "merungut"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["，", "", "", ""],
    ["一定要", "yí dìng yào", "must", "mesti"],
    ["把那个", "bǎ nà ge", "that", "itu"],
    ["“", "", "", ""],
    ["好人", "hǎo rén", "good person", "orang baik"],
    ["”", "", "", ""],
    ["给找到", "gěi zhǎo dào", "find", "menemui"],
    ["。", "", "", ""],
    ["然而", "rán ér", "however", "Namun"],
    ["一直到", "yì zhí dào", "until", "sehingga"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["即将", "jí jiāng", "about to", "hampir"],
    ["出院了", "chū yuàn le", "discharged", "keluar hospital"],
    ["，", "", "", ""],
    ["我始终", "wǒ shǐ zhōng", "I throughout", "saya sepanjang masa"],
    ["都", "dōu", "still", "masih"],
    ["找不到", "zhǎo bú dào", "could not find", "tidak dapat menemui"],
    ["那个", "nà ge", "that", "itu"],
    ["“", "", "", ""],
    ["好人", "hǎo rén", "good person", "orang baik"],
    ["”", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["面对", "miàn duì", "Facing", "Menghadapi"],
    ["一笔", "yì bǐ", "a (sum)", "sejumlah"],
    ["不菲的", "bù fěi de", "considerable", "yang besar"],
    ["手术费", "shǒu shù fèi", "surgery fees", "yuran pembedahan"],
    ["，", "", "", ""],
    ["我用", "wǒ yòng", "I used", "Saya dengan"],
    ["命令的", "mìng lìng de", "commanding", "arahan"],
    ["语气", "yǔ qì", "tone", "nada"],
    ["要求", "yāo qiú", "demanded", "menuntut"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["再", "zài", "again", "sekali lagi"],
    ["仔细", "zǐ xì", "carefully", "dengan teliti"],
    ["想想", "xiǎng xiǎng", "think", "fikirkan"],
    ["那张", "nà zhāng", "that", "itu"],
    ["纸条", "zhǐ tiáo", "note", "nota"],
    ["的", "de", "", ""],
    ["下落", "xià luò", "whereabouts", "di mana"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["迟疑了", "chí yí le", "hesitated", "teragak-agak"],
    ["一下", "yí xià", "for a moment", "sebentar"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["她想不起来了", "tā xiǎng bù qǐ lái le", "she couldn't remember", "dia tidak dapat ingat"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["不停地", "bù tíng de", "continuously", "tanpa henti"],
    ["在", "zài", "in", "di"],
    ["口袋里", "kǒu dai lǐ", "in her pocket", "dalam poket"],
    ["摸来摸去", "mō lái mō qù", "fumbling", "meraba-raba"],
    ["。", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["颤抖着", "chàn dǒu zhe", "tremblingly", "dengan bergetar"],
    ["声音", "shēng yīn", "voice", "suara"],
    ["喊", "hǎn", "shouted", "berseru"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["找着了", "zhǎo zháo le", "found it", "jumpa"],
    ["，", "", "", ""],
    ["真是", "zhēn shì", "really", "sungguh"],
    ["老天有眼", "lǎo tiān yǒu yǎn", "Heaven has eyes", "bertuah"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["一脸", "yì liǎn", "with a face of", "dengan raut"],
    ["惊喜", "jīng xǐ", "surprise and joy", "terkejut dan gembira"],
    ["把", "bǎ", "", ""],
    ["纸条", "zhǐ tiáo", "note", "nota"],
    ["递给我", "dì gěi wǒ", "handed to me", "menyerahkan kepada saya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["用手指", "yòng shǒu zhǐ", "with my finger", "dengan jari"],
    ["按下", "àn xià", "pressed", "menekan"],
    ["那个", "nà ge", "that", "itu"],
    ["号码", "hào mǎ", "number", "nombor"],
    ["——", "", "", ""],
    ["结果", "jié guǒ", "as a result", "hasilnya"],
    ["不通", "bù tōng", "couldn't get through", "tidak dapat dihubungi"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["拨了", "bō le", "dialed", "mendail"],
    ["好几次", "hǎo jǐ cì", "several times", "beberapa kali"],
    ["，", "", "", ""],
    ["都是", "dōu shì", "all were", "semuanya"],
    ["同样的", "tóng yàng de", "the same", "sama"],
    ["结果", "jié guǒ", "result", "keputusan"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["忍不住", "rěn bú zhù", "couldn't help", "tidak tahan"],
    ["对", "duì", "to", "kepada"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["抱怨", "bào yuàn", "complain", "merungut"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["看吧", "kàn ba", "see", "lihatlah"],
    ["！", "", "", ""],
    ["这就是", "zhè jiù shì", "this is", "inilah"],
    ["您", "nín", "you", "awak"],
    ["所", "suǒ", "", ""],
    ["遇见的", "yù jiàn de", "met", "jumpa"],
    ["好人", "hǎo rén", "good person", "orang baik"],
    ["？”", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["却", "què", "however", "namun"],
    ["仍", "réng", "still", "masih"],
    ["为", "wèi", "for", "untuk"],
    ["对方", "duì fāng", "the other party", "pihak lain"],
    ["辩护", "biàn hù", "defend", "mempertahankan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["也许", "yě xǔ", "maybe", "mungkin"],
    ["人家的", "rén jiā de", "his", "dia punya"],
    ["手机", "shǒu jī", "phone", "telefon bimbit"],
    ["正好", "zhèng hǎo", "just happened", "kebetulan"],
    ["没电了", "méi diàn le", "ran out of battery", "bateri habis"],
    ["呢", "ne", "particle", "!"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["明显", "míng xiǎn", "obviously", "jelas"],
    ["没了", "méi le", "lost", "hilang"],
    ["底气", "dǐ qì", "confidence", "keyakinan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["那天", "nà tiān", "That day", "Hari itu"],
    ["的", "de", "", ""],
    ["天气", "tiān qì", "weather", "cuaca"],
    ["晴朗", "qíng lǎng", "clear", "cerah"],
    ["，", "", "", ""],
    ["然而", "rán ér", "however", "namun"],
    ["，", "", "", ""],
    ["阳光", "yáng guāng", "sunshine", "cahaya matahari"],
    ["有多明媚", "yǒu duō míng mèi", "how bright", "betapa terang"],
    ["，", "", "", ""],
    ["我心里", "wǒ xīn lǐ", "in my heart", "dalam hati saya"],
    ["就有", "jiù yǒu", "there is", "terdapat"],
    ["多阴晦", "duō yīn huì", "how gloomy", "betapa gelap"],
    ["。", "", "", ""],
    ["而我", "ér wǒ", "yet I", "namun saya"],
    ["却", "què", "yet", "sebaliknya"],
    ["不敢", "bù gǎn", "dare not", "tidak berani"],
    ["向", "xiàng", "to", "kepada"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["抱怨", "bào yuàn", "complain", "merungut"],
    ["医药费", "yī yào fèi", "medical fees", "yuran perubatan"],
    ["的事", "de shì", "matter", "hal"],
    ["。", "", "", ""],
    ["这件事", "zhè jiàn shì", "this matter", "Perkara ini"],
    ["情以后", "qing yǐ hòu", "after that", "selepas itu"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["在我面前", "zài wǒ miàn qián", "in front of me", "di hadapan saya"],
    ["像个", "xiàng ge", "like a", "seperti"],
    ["犯人", "fàn rén", "prisoner", "pesalah"],
    ["似的", "shì de", "as if", "seolah-olah"],
    ["，", "", "", ""],
    ["一天到晚", "yì tiān dào wǎn", "all day long", "sepanjang hari"],
    ["大气", "dà qì", "heavily", "nafas lega"],
    ["都不敢喘", "dōu bù gǎn chuǎn", "didn't dare to breathe", "tidak berani bernafas"],
    ["，", "", "", ""],
    ["让人", "ràng rén", "making people", "membuatkan orang"],
    ["心疼不已", "xīn téng bù yǐ", "heart ache endlessly", "sangat menyayat hati"],
    ["。", "", "", ""],
    ["这", "zhè", "this", "Ini"],
    ["反而", "fǎn ér", "instead", "pula"],
    ["更增加了", "gèng zēng jiā le", "increased", "menambahkan"],
    ["我对", "wǒ duì", "my towards", "saya terhadap"],
    ["那个", "nà ge", "that", "itu"],
    ["“", "", "", ""],
    ["好人", "hǎo rén", "good person", "orang baik"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["愤恨", "fèn hèn", "resentment", "kemarahan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["一天", "yì tiān", "One day", "Suatu hari"],
    ["我家", "wǒ jiā", "my house", "rumah saya"],
    ["门铃响了", "mén líng xiǎng le", "doorbell rang", "loceng pintu berbunyi"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["开门一看", "kāi mén yí kàn", "opened the door and looked", "buka pintu dan lihat"],
    ["，", "", "", ""],
    ["是", "shì", "was", "ialah"],
    ["一位", "yí wèi", "a", "seorang"],
    ["头发花白", "tóu fa huā bái", "grey-haired", "beruban"],
    ["、", "", "", ""],
    ["背脊向偻", "bèi jǐ xiàng lóu", "hunchbacked", "bongkok"],
    ["的", "de", "", ""],
    ["大叔", "dà shū", "uncle", "pakcik"],
    ["，", "", "", ""],
    ["手里", "shǒu lǐ", "in hand", "di tangan"],
    ["还", "hái", "still", "masih"],
    ["拎着", "līn zhe", "carrying", "menjinjing"],
    ["一袋", "yí dài", "a bag of", "sebungkus"],
    ["水果", "shuǐ guǒ", "fruit", "buah"],
    ["，", "", "", ""],
    ["说是", "shuō shì", "said he was", "katanya"],
    ["找", "zhǎo", "looking for", "mencari"],
    ["一位", "yí wèi", "a", "seorang"],
    ["上个月", "shàng gè yuè", "last month", "bulan lalu"],
    ["被他", "bèi tā", "by him", "oleh dia"],
    ["撞伤的", "zhuàng shāng de", "knocked down", "dilanggar cedera"],
    ["大姊", "dà jiě", "sister", "kakak"],
    ["。", "", "", ""],
    ["未等", "wèi děng", "before", "sebelum sempat"],
    ["我", "wǒ", "I", "saya"],
    ["开口", "kāi kǒu", "speak", "buka mulut"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["就", "jiù", "then", "pun"],
    ["赶紧", "gǎn jǐn", "hurriedly", "cepat-cepat"],
    ["请他", "qǐng tā", "invited him", "menjemputnya"],
    ["进屋里坐", "jìn wū lǐ zuò", "inside to sit", "masuk duduk"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["坐下来之后", "zuò xià lái zhī hòu", "after he sat down", "Selepas dia duduk"],
    ["，", "", "", ""],
    ["吞吞吐吐地", "tūn tūn tǔ tǔ de", "hesitantly", "dengan teragak-agak"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["原本", "yuán běn", "originally", "Sepatutnya"],
    ["第二天", "dì èr tiān", "the next day", "esoknya"],
    ["我", "wǒ", "I", "saya"],
    ["就要", "jiù yào", "was going to", "hendak"],
    ["来", "lái", "come", "datang"],
    ["探望你", "tàn wàng nǐ", "visit you", "melawat awak"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["家里", "jiā lǐ", "at home", "di rumah"],
    ["出了点事", "chū le diǎn shì", "something came up", "ada hal"],
    ["，", "", "", ""],
    ["一直", "yì zhí", "always", "sentiasa"],
    ["脱不了身", "tuō bù liǎo shēn", "couldn't get away", "tidak dapat menguruskan diri"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["我一听", "wǒ yì tīng", "As soon as I heard", "Sebaik sahaja saya dengar"],
    ["就", "jiù", "then", "lalu"],
    ["拿出", "ná chū", "took out", "mengeluarkan"],
    ["账单", "zhàng dān", "bill", "bil"],
    ["，", "", "", ""],
    ["打断", "dǎ duàn", "interrupted", "memotong"],
    ["他的话", "tā de huà", "his words", "kata-katanya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["大叔", "dà shū", "Uncle", "Pakcik"],
    ["别说了", "bié shuō le", "don't say anymore", "jangan cakap lagi"],
    ["，", "", "", ""],
    ["三万元的", "sān wàn yuán de", "thirty thousand yuan", "tiga puluh ribu yuan"],
    ["住院费", "zhù yuàn fèi", "hospitalization fees", "yuran hospital"],
    ["，", "", "", ""],
    ["你要", "nǐ yào", "you must", "awak mesti"],
    ["全权负责", "quán quán fù zé", "take full responsibility", "bertanggungjawab sepenuhnya"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "Ibu"],
    ["瞪了", "dèng le", "glared at", "merenung"],
    ["我一眼", "wǒ yì yǎn", "me one glance", "saya"],
    ["，", "", "", ""],
    ["连忙", "lián máng", "hurriedly", "cepat-cepat"],
    ["打圆场", "dǎ yuán chǎng", "mediated", "menjadi orang tengah"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你是", "nǐ shì", "are you", "awak"],
    ["怎么", "zěn me", "how", "macam mana"],
    ["找到", "zhǎo dào", "find", "cari"],
    ["这里的", "zhè lǐ de", "this place", "ke sini"],
    ["？”", "", "", ""],
    ["大叔", "dà shū", "uncle", "Pakcik"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那天", "nà tiān", "that day", "hari itu"],
    ["你走后", "nǐ zǒu hòu", "after you left", "selepas awak pergi"],
    ["，", "", "", ""],
    ["我不放心", "wǒ bú fàng xīn", "I was worried", "saya tidak puas hati"],
    ["，", "", "", ""],
    ["其实", "qí shí", "actually", "sebenarnya"],
    ["我有", "wǒ yǒu", "I had", "saya ada"],
    ["悄悄跟着", "qiāo qiāo gēn zhe", "quietly followed", "ikut secara senyap"],
    ["，", "", "", ""],
    ["直到", "zhí dào", "until", "sehingga"],
    ["你进家门", "nǐ jìn jiā mén", "you entered your house", "awak masuk rumah"],
    ["我", "wǒ", "I", "saya"],
    ["才", "cái", "only then", "baru"],
    ["离开", "lí kāi", "left", "pergi"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["他", "tā", "He", "Dia"],
    ["忽而", "hū ér", "suddenly", "tiba-tiba"],
    ["把头", "bǎ tóu", "head", "kepala"],
    ["转向我", "zhuǎn xiàng wǒ", "turned towards me", "memusing ke arah saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["请假", "qǐng jià", "took leave", "ambil cuti"],
    ["照顾", "zhào gù", "care for", "jaga"],
    ["你母亲", "nǐ mǔ qīn", "your mother", "ibu awak"],
    ["，", "", "", ""],
    ["肯定", "kěn dìng", "must have", "pasti"],
    ["被扣了", "bèi kòu le", "had deducted", "dipotong"],
    ["薪水吧", "xīn shuǐ ba", "salary right", "gaji kan"],
    ["？", "", "", ""],
    ["一并", "yí bìng", "together", "sekali"],
    ["算到", "suàn dào", "count on", "kirakan ke"],
    ["我头上", "wǒ tóu shàng", "my head", "saya"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["接着", "jiē zhe", "then", "Kemudian"],
    ["他", "tā", "he", "dia"],
    ["不好意思地", "bù hǎo yì si de", "embarrassedly", "dengan malu"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["一下", "yí xià", "at once", "sekali"],
    ["拿不出", "ná bù chū", "can't come up with", "tidak dapat keluarkan"],
    ["这么多", "zhè me duō", "so much", "sebanyak itu"],
    ["，", "", "", ""],
    ["我先", "wǒ xiān", "let me first", "saya dulu"],
    ["给你", "gěi nǐ", "give you", "beri awak"],
    ["写个", "xiě ge", "write a", "tulis"],
    ["欠条", "qiàn tiáo", "IOU", "nota hutang"],
    ["好么", "hǎo me", "okay", "boleh"],
    ["？", "", "", ""],
    ["你放心", "nǐ fàng xīn", "don't worry", "awak tenang"],
    ["，", "", "", ""],
    ["我一定会", "wǒ yí dìng huì", "I definitely will", "saya pasti akan"],
    ["尽快", "jǐn kuài", "as soon as possible", "secepat mungkin"],
    ["还清", "huán qīng", "pay off", "bayar"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["没好气地", "méi hǎo qì de", "impatiently", "dengan tidak sabar"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你上次", "nǐ shàng cì", "you last time", "awak kali lepas"],
    ["给的", "gěi de", "gave", "beri"],
    ["联络号码", "lián luò hào mǎ", "contact number", "nombor hubungan"],
    ["根本", "gēn běn", "completely", "langsung"],
    ["打不通", "dǎ bù tōng", "couldn't get through", "tidak dapat dihubungi"],
    ["，", "", "", ""],
    ["这次", "zhè cì", "this time", "kali ini"],
    ["又来", "yòu lái", "again come", "lagi datang"],
    ["一张", "yì zhāng", "a", "sehelai"],
    ["没用的", "méi yòng de", "useless", "tak berguna"],
    ["纸条", "zhǐ tiáo", "note", "nota"],
    ["？", "", "", ""],
    ["你以为", "nǐ yǐ wéi", "you think", "awak fikir"],
    ["同样的", "tóng yàng de", "the same", "sama"],
    ["招式", "zhāo shì", "trick", "taktik"],
    ["还可以", "hái kě yǐ", "still can", "masih boleh"],
    ["用", "yòng", "use", "guna"],
    ["第二次吗", "dì èr cì ma", "a second time", "kali kedua"],
    ["？”", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["明白了", "míng bái le", "understood", "faham"],
    ["我的意思", "wǒ de yì si", "what I meant", "maksud saya"],
    ["，", "", "", ""],
    ["脸红了", "liǎn hóng le", "blushed", "muka merah"],
    ["，", "", "", ""],
    ["低下头", "dī xià tóu", "lowered his head", "menunduk"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["对不起", "duì bù qǐ", "I'm sorry", "Maaf"],
    ["，", "", "", ""],
    ["那天", "nà tiān", "that day", "hari itu"],
    ["我扶", "wǒ fú", "I helped", "saya tolong"],
    ["你母亲时", "nǐ mǔ qīn shí", "your mother when", "ibu awak masa"],
    ["，", "", "", ""],
    ["可能", "kě néng", "maybe", "mungkin"],
    ["把手机", "bǎ shǒu jī", "phone", "telefon bimbit"],
    ["给弄丢了", "gěi nòng diū le", "lost", "hilang"],
    ["，", "", "", ""],
    ["后来", "hòu lái", "later", "lepas tu"],
    ["换了", "huàn le", "changed", "tukar"],
    ["新手机号码", "xīn shǒu jī hào mǎ", "new phone number", "nombor telefon baru"],
    ["。", "", "", ""],
    ["我不是", "wǒ bú shì", "I am not", "Saya bukan"],
    ["存心", "cún xīn", "intentionally", "sengaja"],
    ["骗", "piàn", "deceive", "menipu"],
    ["你们的", "nǐ men de", "you all", "awak"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["说完", "shuō wán", "After saying that", "Selepas berkata begitu"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["一拐一拐地", "yì guǎi yì guǎi de", "limping", "terhincut-hincut"],
    ["走向", "zǒu xiàng", "walked towards", "ke arah"],
    ["书桌", "shū zhuō", "desk", "meja tulis"],
    ["，", "", "", ""],
    ["准备", "zhǔn bèi", "ready to", "bersiap untuk"],
    ["写", "xiě", "write", "menulis"],
    ["欠条", "qiàn tiáo", "IOU", "nota hutang"],
    ["。", "", "", ""],
    ["他", "tā", "he", "Dia"],
    ["似乎", "sì hū", "seemed", "seolah-olah"],
    ["已", "yǐ", "already", "sudah"],
    ["注意到", "zhù yì dào", "noticed", "perasan"],
    ["我", "wǒ", "I", "saya"],
    ["有意无意地", "yǒu yì wú yì de", "intentionally or not", "sengaja atau tidak"],
    ["看着", "kàn zhe", "looking at", "melihat"],
    ["他", "tā", "his", "dia punya"],
    ["不太自然的", "bú tài zì rán de", "unnatural", "tidak semula jadi"],
    ["走姿", "zǒu zī", "walking posture", "cara jalan"],
    ["。", "", "", ""],
    ["于是", "yú shì", "so", "Maka"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["提起", "tí qǐ", "lifted", "mengangkat"],
    ["裤脚", "kù jiǎo", "trouser leg", "labuh seluar"],
    ["，", "", "", ""],
    ["坦然地说", "tǎn rán de shuō", "and said calmly", "dan berkata dengan tenang"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我这", "wǒ zhè", "my these", "saya ini"],
    ["两条腿", "liǎng tiáo tuǐ", "two legs", "dua batang kaki"],
    ["在", "zài", "in", "dalam"],
    ["车祸中", "chē huò zhōng", "a car accident", "kemalangan jalan raya"],
    ["没了", "méi le", "lost", "hilang"],
    ["，", "", "", ""],
    ["撞我的人", "zhuàng wǒ de rén", "the person who hit me", "orang yang melanggar saya"],
    ["肇祸后", "zhào huò hòu", "after the accident", "selepas kemalangan"],
    ["逃逸", "táo yì", "fled", "melarikan diri"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["李传鹏", "lǐ chuán péng", "Li Chuanpeng", "Li Chuanpeng"],
    ["《", "", "", ""],
    ["两张纸条", "liǎng zhāng zhǐ tiáo", "Two Notes", "Dua Nota"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
